import { beforeEach, describe, expect, it } from "vitest";

import {
  createFiveSAudit,
  saveFiveSAuditDraft,
  setFiveSAudits,
} from "@/lib/five-s/audit-store";
import type {
  FiveSQuestion,
  FiveSQuestionStatus,
  FiveSSection,
} from "@/features/five-s/types/five-s";

function question(
  id: string,
  score: number | null | undefined,
  status: FiveSQuestionStatus,
  maxScore = 2,
): FiveSQuestion {
  return {
    id,
    category: "Sort",
    question: id,
    maxScore,
    score: score as number | null,
    status,
    actionRequired: false,
  };
}

function section(questions: FiveSQuestion[]): FiveSSection {
  return { category: "Sort", description: "", questions, score: 0, maxScore: 0 };
}

function create(sections: FiveSSection[]) {
  return createFiveSAudit({
    title: "generated by store",
    plant: "Test Plant",
    department: "Production",
    area: "Zone D",
    auditor: "Test Auditor",
    dueDate: "2026-09-01",
    sections,
  });
}

describe("audit store score and completion behavior", () => {
  beforeEach(() => setFiveSAudits([]));

  it("sums scores 0, 1, and 2 and respects per-question maxScore", () => {
    const audit = create([section([
      question("zero", 0, "Fail"),
      question("one", 1, "Pass"),
      question("two", 2, "Pass"),
      question("five-point", 5, "Pass", 5),
    ])]);
    expect(audit).toMatchObject({ score: 8, maxScore: 11, completionPercentage: 100 });
  });

  it.each([
    ["score zero is answered", 0, "Fail", 100],
    ["score null with Pass status is answered", null, "Pass", 100],
    ["score undefined with Pass status is answered", undefined, "Pass", 100],
    ["Not Started is unanswered even with score", 2, "Not Started", 0],
    ["NA is answered", null, "NA", 100],
  ] as const)("%s", (_label, score, status, completionPercentage) => {
    expect(create([section([question("q", score, status)])]).completionPercentage).toBe(
      completionPercentage,
    );
  });

  it("treats undefined and null as zero score", () => {
    const audit = create([section([
      question("null", null, "Pass"),
      question("undefined", undefined, "Pass"),
    ])]);
    expect(audit.score).toBe(0);
  });

  it("excludes NA from earned score but retains its maximum-score denominator", () => {
    const audit = create([section([
      question("na-with-score", 2, "NA"),
      question("pass", 2, "Pass"),
    ])]);
    expect(audit).toMatchObject({ score: 2, maxScore: 4, completionPercentage: 100 });
  });

  it("rounds partially completed audits and preserves fully completed audits", () => {
    const audit = create([section([
      question("answered", 0, "Fail"),
      question("unanswered-1", null, "Not Started"),
      question("unanswered-2", null, "Not Started"),
    ])]);
    expect(audit.completionPercentage).toBe(33);

    const completed = saveFiveSAuditDraft(audit.id, [section([
      question("answered", 0, "Fail"),
      question("answered-2", 1, "Pass"),
      question("answered-3", 2, "Pass"),
    ])]);
    expect(completed).toMatchObject({ score: 3, maxScore: 6, completionPercentage: 100 });
  });
});
