"use client";

import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export interface ReportTrendPoint { label: string; score?: number; value?: number }
export interface StatusPoint { status: string; value: number }

const tooltip = { border: "1px solid var(--border)", borderRadius: 10, background: "var(--popover)", color: "var(--popover-foreground)", boxShadow: "0 12px 30px -20px rgb(15 23 42 / .45)", fontSize: 12 };

function Frame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <Card className="min-w-0 overflow-hidden"><CardHeader className="border-b bg-muted/[0.08] pb-3"><CardTitle className="text-base">{title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{description}</p></CardHeader><CardContent className="h-[275px] px-2 pb-4 pt-5 sm:px-4">{children}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <div className="grid h-full place-items-center text-sm text-muted-foreground">{text}</div>; }

export function ReportAuditTrend({ data }: { data: ReportTrendPoint[] }) { return <Frame title="Audit Performance" description="Average compliance score over the reporting period.">{data.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:18,left:-15,bottom:3}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}} /><YAxis domain={[0,100]} tickFormatter={(v)=>`${v}%`} tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}} /><Tooltip contentStyle={tooltip} formatter={(v)=>[`${v}%`,"Compliance"]} /><Line type="monotone" dataKey="score" stroke="var(--primary)" strokeWidth={2.5} dot={{r:3,fill:"var(--card)",strokeWidth:2}} activeDot={{r:5}} /></LineChart></ResponsiveContainer>:<Empty text="No completed audit data" />}</Frame>; }

export function CostSavingTrend({ data }: { data: ReportTrendPoint[] }) { return <Frame title="Improvement Value" description="Recorded savings from approved corrective improvements.">{data.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:8,right:18,left:-8,bottom:3}}><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}} /><YAxis tickFormatter={(v)=>`₹${Math.round(v/1000)}K`} tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}} /><Tooltip contentStyle={tooltip} formatter={(v)=>[`₹${Number(v).toLocaleString("en-IN")}`,"Cost saving"]} /><Bar dataKey="value" fill="var(--primary)" radius={[5,5,0,0]} maxBarSize={36} /></BarChart></ResponsiveContainer>:<Empty text="No approved cost-saving data" />}</Frame>; }

export function ActionFlowChart({ data }: { data: StatusPoint[] }) { return <Frame title="Action Status Flow" description="Action workload grouped by the same stages used in the lifecycle timeline.">{data.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top:5,right:24,left:18,bottom:3}}><CartesianGrid horizontal={false} stroke="var(--border)" strokeDasharray="3 3" /><XAxis type="number" allowDecimals={false} tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--muted-foreground)"}} /><YAxis type="category" dataKey="status" width={138} tickLine={false} axisLine={false} tick={{fontSize:11,fill:"var(--foreground)"}} /><Tooltip contentStyle={tooltip} /><Bar dataKey="value" fill="var(--primary)" radius={[0,5,5,0]} maxBarSize={22} /></BarChart></ResponsiveContainer>:<Empty text="No action workflow data" />}</Frame>; }
